### ISSUE TITLE
Steps data not working

### ISSUE THREAD

**Issue by Gishan86** [cyberjunky/python-garminconnect#168] opened 2023-10-15 15:13 UTC
Hi, did Garmin change the url for steps data?
Neither one of these work:

`json = api.get_daily_steps("2023-01-01", "2023-10-01")`
Throws garth.exc.GarthHTTPError: Error in request: 400 Client Error: Bad Request for url: https://connectapi.garmin.com/usersummary-service/stats/steps/daily/2023-01-01/2023-10-01

`json = api.get_steps_data("2023-10-17")`
Returns an empty list.

On https://connect.garmin.com there is step data for 2023-10-17.
Other routes like get_weigh_ins work and return data.

```
Python 3.12
garminconnect==0.2.8
garth==0.4.38
```

**Comment by matin** [comment] 2023-10-16 00:14
1. iirc, there's a 28-day limit for the date period
2. 2023-10-17 is currently in the future. No result is correct

**Comment by Gishan86** [comment] 2023-10-16 14:49
Thanks for your quick response!

1. I've also tried 2022-10-15 to 2022-10-20 and 2023-10-01 to 2023-10-05
which both resulted in the same exception

2. Yeah, that was a typo, not a time traveller. :)
With 2022-10-18 I get results but they are all empty.
It returns an empty entry for every 15 minutes of the day like this:

`[{'startGMT': '2022-10-17T22:00:00.0', 'endGMT': '2022-10-17T22:15:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T22:15:00.0', 'endGMT': '2022-10-17T22:30:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T22:30:00.0', 'endGMT': '2022-10-17T22:45:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T22:45:00.0', 'endGMT': '2022-10-17T23:00:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T23:00:00.0', 'endGMT': '2022-10-17T23:15:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T23:15:00.0', 'endGMT': '2022-10-17T23:30:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T23:30:00.0', 'endGMT': '2022-10-17T23:45:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-17T23:45:00.0', 'endGMT': '2022-10-18T00:00:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-18T00:00:00.0', 'endGMT': '2022-10-18T00:15:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-18T00:15:00.0', 'endGMT': '2022-10-18T00:30:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-18T00:30:00.0', 'endGMT': '2022-10-18T00:45:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-18T00:45:00.0', 'endGMT': '2022-10-18T01:00:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-18T01:00:00.0', 'endGMT': '2022-10-18T01:15:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, {'startGMT': '2022-10-18T01:15:00.0', 'endGMT': '2022-10-18T01:30:00.0', 'steps': 0, 'pushes': 0, 'primaryActivityLevel': 'none', 'activityLevelConstant': True}, ...]`

The web UI shows 17.843 steps for 2022-10-18 though.

**Comment by matin** [comment] 2023-10-16 17:33
weekly works though:
```python
api.garth.connectapi('/usersummary-service/stats/steps/weekly/2022-10-18/52')
```

**Comment by matin** [comment] 2023-10-16 17:40
daily also works for me:

```python
api.get_daily_steps('2022-10-01', '2022-10-28')
```

It looks like the issue is when you want to get the granular data for an individual day.

**Comment by matin** [comment] 2023-10-16 18:06
Figured it out ...

Take a look at this:
![IMG_4340](https://github.com/cyberjunky/python-garminconnect/assets/98985/f8a73eb0-0719-4b30-8970-4aa72ce79202)

You can do the following:

1. Request Garmin loads the old data:
```python
resp = api.garth.post('connectapi', '/wellness-service/wellness/epoch/request/2022-10-18', api=True)
resp.json()
```

Response:
```python
{'userProfilePk': 2591602,
 'calendarDate': '2022-10-18',
 'status': 'SUBMITTED',
 'source': 'USER',
 'ghReloadMetaData': '',
 'createDate': '2023-10-16T17:49:56.980',
 'deviceList': [{'deviceId': 3329978681,
   'deviceName': 'fēnix® 6X - Pro and Sapphire Editions',
   'preferredActivityTracker': True}]}
```

2. Wait a few minutes for the data to load

3. Make the request again

```python
api.get_steps_data("2022-10-18")
```

In other words, this is not a garminconnect or Garth issue. It has to do with how Garmin handles old data.

This issue can be closed as it has instructions to:
1. request weekly steps
2. request daily steps
3. request Garmin load old step data and then request that granular data

HTH!

**Comment by cyberjunky** [comment] 2023-10-28 21:04
> @cyberjunky not sure if you want to add the following endpoint:
> 
> ```python
> api.garth.post('connectapi', '/wellness-service/wellness/epoch/request/2022-10-18', api=True)
> ```
> 
> See the conversation above for context on what it does
@matin 
Can you enlighten me, didn't follow whole issue...
Do I need to add this fixed endpoint with 2022-10-18 at the end?

**Comment by matin** [comment] 2023-10-29 05:26
@cyberjunky created the PR #174 with tests

**Closed** 2023-11-21 08:35 UTC
