### ISSUE TITLE
Daily calories

### ISSUE THREAD

**Issue by jflournoy** [cyberjunky/python-garminconnect#189] opened 2024-01-30 21:57 UTC
Hi there, 

I may have missed it but is there any way to pull daily calories? Thank you!

**Comment by psdupvi** [comment] 2024-03-11 14:27
Use the `get_stats(cdate)` or `get_stats_and_body(cdate)` endpoint, which returns (among many other things) a lot of calorie information.  [In the Demo, this is option 7:
](https://github.com/cyberjunky/python-garminconnect/blob/master/README.md)

cdate is a string

```python
api = init_api(email=os.environ['GARMIN_USERNAME'], password=os.environ['GARMIN_PASSWORD'])

stats_data = api.get_stats('2024-03-10')

# Returns object including the following fields:
{
'userProfileId': 123456789, # Your User ID
...
'totalKilocalories': 4067.0,
 'activeKilocalories': 1874.0,
 'bmrKilocalories': 2193.0,
 'wellnessKilocalories': 4067.0,
 'burnedKilocalories': None, # Always None for me
 'consumedKilocalories': 3937.0, # For me, this comes from MyFitnessPal. Not sure if Garmin has built in calorie consumption tracking
 'remainingKilocalories': 130.0,
'netCalorieGoal': 1770,
...
}
```

Under the hood, `get_stats_and_body` calls `get_stats` which calls `get_user_summary`

**Comment by cyberjunky** [comment] 2024-04-06 08:12
@jflournoy did you manage to get the data you wanted, is there mode needed?

**Comment by jflournoy** [comment] 2024-04-08 18:35
I haven't had a chance to test this out yet but will report back when I do. thank you! I think i just missed this in the example.

**Comment by AnonJohn** [comment] 2024-05-14 14:56
I can confirm that this works.

**Comment by cyberjunky** [comment] 2024-07-06 09:43
Closing since tested and solved, thanks all!

**Closed by cyberjunky** 2024-07-06 09:43 UTC
