### ISSUE TITLE
url_activities

### ISSUE THREAD

**Issue by enydog** [cyberjunky/python-garminconnect#39] opened 2021-02-23 19:16 UTC
May be url_activities = MODERN_URL + '/proxy/activitylist-service/activities/search/activities' 
was changed.

Garmin CLIENT ok
Garmin LOGIIN ok
Error occurred during Garmin Connect Client get activities: Error connecting

**Comment by JVPA** [comment] 2021-02-24 11:59
I have the same problem garminconnect.GarminConnectConnectionError: Error connecting

**Comment by enydog** [comment] 2021-02-24 14:47
BASE_URL = 'https://connect.garmin.com'
SSO_URL = 'https://sso.garmin.com/sso'
MODERN_URL = 'https://connect.garmin.com'
#MODERN_URL = 'https://connect.garmin.com/modern'
SIGNIN_URL = 'https://sso.garmin.com/sso/signin'

**Comment by cyberjunky** [comment] 2021-02-24 20:28
@enydog thanks!
Please try version 0.1.19

**Comment by JVPA** [comment] 2021-02-24 21:24
I have tried the last version and the problem is solved

> @enydog thanks!
> Please try version 0.1.19

I have tried the last version and the problem is solved

**Comment by cyberjunky** [comment] 2021-02-26 10:45
I will close this ticket, users of Home Assistant can run a beta version, or wait until Wednesday for the fix to be included in the new release.

**Closed by cyberjunky** 2021-02-26 10:45 UTC
